### ISSUE TITLE
CSR "misa" reports incorrect RISC-V extensions and is not WARL

### ISSUE THREAD

**Issue by lindemer** [SpinalHDL/VexRiscv#110]
I'm using VexRiscv full on an Arty FPGA board. I've flashed the gateware to ROM and am booting Zephyr RTOS over serial with [flterm](https://github.com/timvideos/flterm). I would like to get the exact RISC-V CPU configuration from the `misa` register like so:
### assembly code
```
get_misa:
    csrr a0, misa
    ret

set_misa:
    csrw misa, a0
    ret
```
### main.c
```
extern int get_misa();
extern void set_misa(int x);

void main(void) {
    int s = get_misa();
    printk("misa = 0x%x\n", s);
    set_misa(0xffffffff);
    s = get_misa();
    printk("misa = 0x%x\n", s);
}
```
### output on VexRiscv
```
*** Booting Zephyr OS build zephyr-v2.1.0  ***
misa = 0x40000042
misa = 0xc3ffffff
```
According to the privileged ISA spec, bits 8 and 12 of `misa` should be set for RV32IM, and the register should be "Write Any Values, Reads Legal Values (WARL)" I ran this code on QEMU's RV32 emulator as a sanity check and got the behavior I expected:
### output on QEMU
```
*** Booting Zephyr OS build zephyr-v2.1.0  ***
misa = 0x40101105
misa = 0x40101105
```

**Comment by Dolu1990** [comment]
Hi,

in VexRiscv MISA is currently at best a read_only register which could be harwired durring elaboration.
But in the config that you are using, MISA isn't enabled at all.

https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/demo/GenFull.scala#L78
https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/plugin/CsrPlugin.scala#L223

The reason that you got a misa = 0x40000042 is because that configuration do not catch wrong CSR accesses (https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/plugin/CsrPlugin.scala#L217)

So basicaly, you would have to customize the configuration to get what you want, i mean at least the read_only.
