### ISSUE TITLE
global accumulator among different custom instruction  

### ISSUE THREAD

**Issue by icewindqz** [SpinalHDL/VexRiscv#151]
I tried to create a set of custom MAC (multiplier–accumulator) instructions which require a global accumulator that need to be shared with multiple instruction. 
This is how I tried to do: I created individual instruction as individual Plugin (I'm taking CustomInstrunction.scala as Example), and instantiate in GenCustom.scala. I'm not sure how to create a global register that can be shared among different custom instruction(or Plugin). 
Do you have an example of it, or do you have any better suggestion to implement it.
Thanks in advance.

**Comment by Dolu1990** [comment]
Hi,

So, you have three solutions : 
- You can have all you instruction in the same plugin
- You can have one of your plugin instanciating the states, and sharing them via the service API (ex : pipeline.service(classOf[DecoderService])
- Same than previous, but instead of using the service API, you can share global stuff in the pipeline using the PipelineThing : 
Ex : 
Define a global thing as : 
https://github.com/SpinalHDL/VexRiscv/blob/95237b23ea2d658cb3e0aa77680ca2851ef5d882/src/main/scala/vexriscv/VexRiscv.scala#L45

Initialise it in one def setup as 
https://github.com/SpinalHDL/VexRiscv/blob/95237b23ea2d658cb3e0aa77680ca2851ef5d882/src/main/scala/vexriscv/plugin/DBusCachedPlugin.scala#L156

read it in all def build as 
pipeline(DEBUG_BYPASS_CACHE)

**Comment by icewindqz** [comment]
thanks
