### ISSUE TITLE
FPU RegFile Details

### ISSUE THREAD

**Issue by gyh1997127** [SpinalHDL/VexRiscv#267]
Hi,

Does VexRiscv implement dedicated floating-point registers? If so, how does it implement double precision registers with a 32-bit base core? Thank you!

**Comment by Dolu1990** [comment]
Hi,

> Does VexRiscv implement dedicated floating-point registers? 

Yes, via the FpuPlugin.

> If so, how does it implement double precision registers with a 32-bit base core? Thank you!

The main change in the core to handle it, is about supporting 64 bits load/store.
So to support it the data cache data path of VexRiscv is crancked up to 64 bits. Else nothing realy change, in the core, as the FpuPlugin does all the job of handeling the FPU register file and data path.

FPU register file : 
https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/ip/fpu/FpuCore.scala#L158

Also note that internaly, floating point values are stored in a recoded format in order to avoid having to deal with subnormal.

**Comment by gyh1997127** [comment]
Appreciate the insight!

**Comment by gyh1997127** [comment]
Sorry about having to dig this one up, but what does the floating-point register file map to if `asyncRegFile == false`? 
I thought it would be BRAM, but the synthesis report says otherwise. Thank you for your insight.

**Comment by Dolu1990** [comment]
> asyncRegFile == false? I thought it would be BRAM

https://github.com/SpinalHDL/VexRiscv/blob/051d140c33ce1480e10bdf76668fceae8ff59bef/src/main/scala/vexriscv/ip/fpu/FpuCore.scala#L285

So, mostly it specify the register file read in a clocked way if turn to false (to easy block ram inferation).
But still, the synthesis tool as the freedoom to emulate that syncronus read with distributed ram in order to save block ram usage. Especialy as there is only 32 words.
